version: '3.9'

services:
 
  mysql_db:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      
  # Wordpress
  wordpress:
    depends_on:
      - mysql_db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress 
        
      volumes: ['./:/var/www/html'] 
volumes:
  mysql: {}
